### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items' 

### ISSUE THREAD

**Issue by smallbirds2** [pablomarin/GPT-Azure-Search-Engine#13]
I tried to follow the guide, did the pip install based on the requirements file and ran the "streamlit Home.py" command. However, I am getting this error: Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/streamlit/web/cli.py", line 177, in main_run
    bootstrap.load_config_options(flag_options=kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/streamlit/web/bootstrap.py", line 342, in load_config_options
    config.get_config_options(force_reparse=True, options_from_flags=options_from_flags)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/streamlit/config.py", line 1144, in get_config_options
    _update_config_with_toml(file_contents, filename)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/streamlit/config.py", line 1025, in _update_config_with_toml
    for name, value in options.items():
AttributeError: 'str' object has no attribute 'items'

**Comment by giorgiosaez** [comment]
You need Python 3.10 or higher. Try following troubleshoot #2. 
https://github.com/pablomarin/GPT-Azure-Search-Engine/edit/main/app/README.md#troubleshoot
